name = input("Enter name:")
age = input("Enter age:")
city = input("Enter city:")
type_name = type(name)
type_age = type(age)
type_city = type(city)
print("\nYour name:", name, "| Type:", type_name)
print("\nYour age:", age, "| Type:", type_age)
print("\nYour city:", city, "| Type:", type_city)